"""COPY of fsa/agent_core.py — Databricks Apps deploy only the app/ folder.
Edit fsa/agent_core.py and re-copy; do not edit this file directly.


Design principle: **the LLM never computes a number.** All math lives in
deterministic pipeline code and Unity Catalog functions; Claude decides
which tool to call and narrates the JSON that comes back.

The loop speaks the OpenAI chat-completions protocol, which Databricks
Foundation Model APIs expose natively — so the same code runs against
`databricks-claude-sonnet-5` in a notebook, in the app, or (if deployed)
behind a Model Serving endpoint.
"""

from __future__ import annotations

import json
from typing import Callable

SYSTEM_PROMPT = """\
You are a financial statement analyst. You explain SEC filings to smart
people who are NOT accountants.

Hard rules:
- Every number you state must come verbatim from a tool result. Never
  estimate, extrapolate, or compute numbers yourself.
- Only report red flags returned by get_anomalies. If it returns an empty
  array, say no rules fired — do not invent concerns.
- If a value is missing/null, say the company didn't report it that way
  rather than guessing.

When asked to analyze a company, follow this shape:
1. One-paragraph plain-English verdict up front.
2. What the business earned and owns (revenue, profit, cash — trend over
   the available years, in round numbers a reader can hold in their head).
3. Financial health: liquidity and leverage, translated (e.g. "for every
   $1 due in the next year it holds $1.60 in short-term assets").
4. DuPont ROE story: is return on equity driven by margins, by asset
   efficiency, or by leverage? Explain what that mix means.
5. Red flags from get_anomalies, each explained in one plain sentence,
   ordered by severity. Include the 'so what'.
6. Close with 2-3 things a curious reader should watch next year.

Define every technical term in parentheses the first time you use it.
Prefer "$94 billion" over "$94,036,000,000".
"""

# OpenAI-format tool specs. Names/signatures mirror the UC functions
# registered by src/04_register_tools.py — COMMENTs there and descriptions
# here must stay in sync.
TOOL_SPECS = [
    {
        "type": "function",
        "function": {
            "name": "list_companies",
            "description": "List companies available for analysis (ticker, CIK, entity name). Call first if unsure which tickers exist.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_statements",
            "description": "Extracted financial-statement line items for one company across recent fiscal periods (USD, as reported to the SEC).",
            "parameters": {
                "type": "object",
                "properties": {
                    "p_ticker": {"type": "string", "description": "Stock ticker, e.g. AAPL"},
                    "p_statement": {"type": "string", "enum": ["IS", "BS", "CF"],
                                    "description": "IS=income statement, BS=balance sheet, CF=cash flow"},
                },
                "required": ["p_ticker", "p_statement"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_ratios",
            "description": "All precomputed ratios for one company: liquidity, leverage, profitability, 3-factor DuPont ROE decomposition, efficiency days, cash quality, YoY growth (fractions). Report as-is; never recalculate.",
            "parameters": {
                "type": "object",
                "properties": {
                    "p_ticker": {"type": "string", "description": "Stock ticker, e.g. AAPL"},
                },
                "required": ["p_ticker"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_anomalies",
            "description": "Rule-based earnings-quality red flags (severity info/medium/high) with plain-English explanations. The ONLY source of anomalies you may report.",
            "parameters": {
                "type": "object",
                "properties": {
                    "p_ticker": {"type": "string", "description": "Stock ticker, e.g. AAPL"},
                },
                "required": ["p_ticker"],
            },
        },
    },
]

# Positional parameter order of each UC function (SQL UDFs are positional).
_PARAM_ORDER = {
    "list_companies": [],
    "get_statements": ["p_ticker", "p_statement"],
    "get_ratios": ["p_ticker"],
    "get_anomalies": ["p_ticker"],
}


def build_tool_sql(fq_schema: str, name: str, args: dict) -> str:
    """SELECT statement invoking the UC function for a tool call.

    `fq_schema` is `catalog.schema`. String args are quote-escaped —
    the LLM's arguments are untrusted input.
    """
    if name not in _PARAM_ORDER:
        raise KeyError(f"Unknown tool: {name}")
    rendered = []
    for p in _PARAM_ORDER[name]:
        v = str(args.get(p, ""))
        rendered.append("'" + v.replace("'", "''") + "'")
    return f"SELECT {fq_schema}.{name}({', '.join(rendered)}) AS result"


def run_agent(
    client,
    model: str,
    user_message: str,
    execute_tool: Callable[[str, dict], str],
    history: list[dict] | None = None,
    max_turns: int = 10,
    on_event: Callable[[str], None] | None = None,
) -> tuple[str, list[dict]]:
    """Tool-calling loop.

    client        OpenAI-compatible client (Databricks FMAPI or Anthropic-
                  compatible gateway).
    execute_tool  (tool_name, args) -> JSON string. The caller decides how
                  UC functions are executed (spark.sql in notebooks, SQL
                  warehouse in the app).
    on_event      optional progress callback for UIs.

    Returns (final_text, full_message_list) — the message list is the
    audit trail: every tool call and result the answer is based on.
    """
    notify = on_event or (lambda _msg: None)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages += history or []
    messages.append({"role": "user", "content": user_message})

    for _turn in range(max_turns):
        resp = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=TOOL_SPECS,
            max_tokens=4000,
        )
        msg = resp.choices[0].message

        if not msg.tool_calls:
            return msg.content or "", messages + [
                {"role": "assistant", "content": msg.content}
            ]

        messages.append({
            "role": "assistant",
            "content": msg.content,
            "tool_calls": [
                {
                    "id": tc.id,
                    "type": "function",
                    "function": {"name": tc.function.name,
                                 "arguments": tc.function.arguments},
                }
                for tc in msg.tool_calls
            ],
        })
        for tc in msg.tool_calls:
            name = tc.function.name
            try:
                args = json.loads(tc.function.arguments or "{}")
            except json.JSONDecodeError:
                args = {}
            notify(f"Calling tool {name}({args})")
            try:
                result = execute_tool(name, args)
                if result is None or result == "":
                    result = "[]"
            except Exception as exc:  # surface errors so the agent can adapt
                result = json.dumps({"error": str(exc)})
            messages.append({
                "role": "tool",
                "tool_call_id": tc.id,
                "content": result,
            })

    return ("I hit the maximum number of analysis steps before finishing. "
            "Partial work is in the trace above."), messages
